samplesheet:     "../../docs/samplesheet.csv"
compass_vcf_dir: "/hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/illumina/gvcfs"
asm_dir:         "/hps/nobackup/iqbal/mbhall/tech_wars/analysis/assembly/results"
data_dir:        "/hps/nobackup/iqbal/mbhall/tech_wars/data/QC/subsampled"
genome_size:     4411532
h37rv:
  genome: "resources/h37rv.fa"
  mask:   "resources/compass-mask.bed"
containers:
  conda:     "docker://continuumio/miniconda3:4.7.12"
  bcftools:  "docker://quay.io/biocontainers/bcftools:1.13--h3a49de5_0"
  varifier:  "docker://quay.io/iqballab/varifier:3c8152a"
  snp-dists: "docker://quay.io/biocontainers/snp-dists:0.7.0--hed695b0_0"
  psdm:      "docker://quay.io/mbhall88/psdm:0.1.0"
  samtools:  "docker://quay.io/biocontainers/samtools:1.13--h8c37831_0"
  happy:     "docker://quay.io/biocontainers/hap.py:0.3.14--py27h5c5a3ab_0"
envs:
  aln_tools:            "envs/aln_tools.yaml"
  filter:               "envs/filter.yaml"
  varifier:             "envs/varifier.yaml"
  concordance:          "envs/concordance.yaml"
  consensus:            "envs/consensus.yaml"
  dotplot:              "envs/dotplot.yaml"
  plot_concordance:     "envs/plot_concordance.yaml"
  plot_truth_eval:      "envs/plot_truth_eval.yaml"
  distance:             "envs/distance.yaml"
  plot_distance_matrix: "envs/plot_distance_matrix.yaml"
  mixed_self_distance:  "envs/mixed_self_distance.yaml"
  bcftools_dotplot:     "envs/dotplot.yaml"
  happy:                "envs/happy.yaml"
scripts:
  filter:               "scripts/apply_filters.py"
  concordance:          "scripts/concordance.py"
  consensus:            "scripts/consensus.py"
  distance:             "scripts/distance.py"
  dotplot:              "scripts/distance_dot_plot.py"
  plot_concordance:     "scripts/plot_concordance.py"
  plot_truth_eval:      "scripts/plot_truth_eval.py"
  plot_distance_matrix: "scripts/plot_distance_matrix.py"
  mixed_self_distance:  "scripts/mixed_self_distance.py"
  bcftools_dotplot:     "scripts/bcftools_dotplot.py"

# filters for nanopore bcftools calls
filters:
  min_depth:       5
  min_fed:         0.2
  max_depth:       0
  min_qual:        25
  min_strand_bias: 1
  min_bqb:         0
  min_mqb:         0
  min_rpb:         0
  max_sgb:         0
  min_vdb:         0.00001
  min_mq:          30
  min_frs:         0.90
  # min_rqbz:        -2.6
  # max_rqbz:        3.0
  # max_scbz:        2.2


assemblies:
  mada_101:  "flye"
  mada_102:  "flye"
  mada_104:  "flye"
  mada_130:  "flye"
  mada_116:  "flye"
  mada_1-44: "flye"
  mada_132:  "flye"
  mada_125:  "flye"
